name: New_workflow
on:  
 push:
  branches:
    - dev
jobs: 
    setup:
     runs-on: ubuntu-latest
     steps:
      - run: echo "Running"
    build:
     needs: setup
     runs-on: ubuntu-latest
     steps:
      - run: echo "dependency"
    test:
     needs: build
     runs-on: ubuntu-latest
     steps:
      - run: echo "testingggg"