name: Output information
on:  
     pull_request:
        types: opened
     workflow_dispatch:
jobs: 
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Github context    # github action context to acces information about the workflow runs, runner env nd steps
              run: echo "${{toJson(github)}}"    #functions/experssion - to progrramatically set variables in workflow files nd acces context

              # Runs a single command using the runners shell
            - name: Print Greestings
              run: echo Hello, world!

      # Runs a set of commands using the runners shell
            - name: Print Goodbye
              run: echo Done_Goodbye!!