name: Output information
on:  workflow_dispatch
jobs: 
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output Github context    # github action context to acces information about the workflow runs, runner env nd steps
              run: echo "${{toJson(github)}}"    #functions/experssion - to progrramatically set variables in workflow files nd acces context
            